name: object_finder
description: "ObjectFinder is a powerful Dart extension on Object? that simplifies safe type checking, dynamic value conversion, and nested object access with default values. It supports primitives, lists, maps, and custom conversion via builders."
version: 1.0.0
repository: https://github.com/Mohiuddin655-PUB/object_finder

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0